apiVersion: apps/v1
kind: Deployment
metadata:
  name: studymate-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studymate
  template:
    metadata:
      labels:
        app: studymate
    spec:
      containers:
      - name: studymate-container
        image: siyakusumakar/studymate-app:v1
        ports:
        - containerPort: 8501